version: "3.8"
services:
  db:
    build: ./database/
    volumes:
      - ./tmp/db:/var/lib/postgresql/database
  app :
    build: ./app/
    ports:
      - '8000:8000'
    env_file:
      - './app/.env' 
    depends_on:
      - "db"
    environment:
      WAIT_HOSTS: db:5432
  